### PR TITLE
Fallback to /proc/$pid/mem when process_vm_readv() is unavailabe

### PR DESCRIPTION
**Pull request by sebageek**
If the Linux kernel was built without support for process_vm_readv()
(CONFIG_CROSS_MEMORY_ATTACH is unset in kernel config) a call to this
function will fail with Function not implemented (os error 38) aka
ENOSYS. To still support reading process memory on this platform we
fallback to reading /proc/$pid/mem.

---
This is intended as a fix for benfred/py-spy/issues/22. To reproduce this I recompiled my current kernel with `CONFIG_CROSS_MEMORY_ATTACH` disabled.
```
$ uname -r
5.10.4no-proc-mem-attach
$ grep CONFIG_CROSS_MEMORY_ATTACH /boot/config-$(uname -r)
# CONFIG_CROSS_MEMORY_ATTACH is not set
```
This yielded the `Error: Function not implemented (os error 38)`. The patch in this PR subsequently fixed this error.

I'm still a bit unhappy with the fallback, as each time memory is read an attempt to use `process_vm_readv()` is made, which is one extra syscall per read. Additionally the filehandle to `procmem` could be cached per pid, saving two additional syscalls (open, close). This might lead to an API change though, so I wanted to discuss this before wildly implementing something. In any case, the code in this PR shouldn't change the performance for current users of this library. It will only be slower in cases where it would have errored out beforehand.

Shoutout to @eqv for rust support!

### CODE REVIEW

**Comment by hartwork** [comment]
@sebageek CI is green now on `master` if you feel like a rebase :tada:

**Review by benfred — APPROVED** [review]

**Comment by benfred** [comment]
Thanks for this! This helps a lot - I'm surprised how many people hit this problem with py-spy

**Comment by nehaljwani** [comment]
@benfred Could you please cut a release with this patch? The 0.2.0 crate doesn't have this change. Also, the tags on the GH repo are not in sync :)

**Comment by nehaljwani** [comment]
The 0.2.0 crate doesn't have this change.

**Comment by benfred** [comment]
@nehaljwani I've pushed out 0.2.1 to crates.io with this change (and am in the process of getting this change into dependant  packages like remoteprocess/py-spy).

**Pull request merged**
